### PR TITLE
Updated to support React 17

### PR DESCRIPTION
**Pull request by kevinfarrugia**
## What's Changing

No new features but upgrading to support React 17 and therefore a breaking change.

## Change Type

- [ ] `documentation`
- [ ] `patch`
- [ ] `minor`
- [x] `major`

### CODE REVIEW

**Comment by zalcode** [comment]
hi @kevinfarrugia 
when you merge this PR ?
image
the current v3 is still using old deps

**Comment by alex-udisc** [comment]
Hey @kevinfarrugia! I'm looking to use this carousel in a nextJS app using React 17. Any chance this gets merged soon? I'm am trying to test this version locally, but I'm not totally sure how to pull down this change as an `npm` module.

**Comment by kevinfarrugia** [comment]
Hi @alex-udisc I will take a look this weekend. What issues are you encountering when running it on React 17 please?

**Comment by kevinfarrugia** [comment]
@alex-udisc I created a new NextJS project using `react: 17.0.2` and `react-glider: 3.0.0` and it is working correctly. As such, I expect that it should work for you too.

Could you please help me understand what issue you are encountering when using React 17 please?

Repo: https://github.com/kevinfarrugia/next-react-glider
Demo: https://next-react-glider.vercel.app/

**Comment by alex-udisc** [comment]
> @alex-udisc I created a new NextJS project using `react: 17.0.2` and `react-glider: 3.0.0` and it is working correctly. As such, I expect that it should work for you too.
> 
> Could you please help me understand what issue you are encountering when using React 17 please?
> 
> Repo: https://github.com/kevinfarrugia/next-react-glider Demo: https://next-react-glider.vercel.app/

@kevinfarrugia Thanks for responding, let me try to explain why I wrote to you in the first place. 

When I install react-glider@3.0.0, React 16 is still a peer dependency:

Screen Shot 2022-01-31 at 12 35 01 PM


I think this is caused by other dependencies still requiring react 16. I guess I'm looking for React 17 support that will not require React 16 in any way. Does this make sense?

**Comment by kevinfarrugia** [comment]
Understood. Will look into it.

**Comment by kevinfarrugia** [comment]
`v3.0.1` should resolve the issue with React since the previous version had a peerDependency on React v16.

Storybook update will be done in a separate PR. See #99

**Pull request closed without merging**
